version: '3'
services:
  myspringboot:
    image: muzafferjoya/spring-boot-poc:latest
    ports:
      - "8080:8080"
    deploy:
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
