apiVersion: apps/v1
kind: Deployment
metadata:
  name: poc
spec:
  selector:
    matchLabels:
      app: poc
  replicas: 1
  template:
    metadata:
      labels:
        app: poc
    spec:
      containers:
      - name: poc
        image: muzafferjoya/sp-boot-poc:21
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: poc
spec:
  selector:
    app: poc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30011
  type: NodePort
