apiVersion: apps/v1
kind: Deployment
metadata:
  name: poc
spec:
  selector:
    matchLabels:
      app: poc
  replicas: 1
  template:
    metadata:
      labels:
        app: poc
    spec:
      containers:
      - name: poc
        image: muzafferjoya/sp-boot-poc:latest
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
