apiVersion: apps/v1
kind: Deployment
metadata:
  name: sp-boot-poc:2
spec:
  selector:
    matchLabels:
      app: sp-boot-poc:2
  replicas: 1
  template:
    metadata:
      labels:
        app: sp-boot-poc:2
    spec:
      containers:
      - name: sp-boot-poc:2
        image: muzafferjoya/sp-boot-poc:2
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: sp-boot-poc:2
spec:
  selector:
    app: sp-boot-poc:2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30011
  type: NodePort
